#!/usr/bin/env python3
"""Validate the node graph and regenerate the generated section of the README.

    python3 tools/build.py           # validate, then rewrite README
    python3 tools/build.py --check   # validate only, fail if README is stale
"""

import sys

from graph import (
    ROOT,
    Problem,
    clean,
    diagram,
    load_all,
    members_of,
    primary_url,
)

README = ROOT / "README.md"
BEGIN = "<!-- BEGIN GENERATED -->"
END = "<!-- END GENERATED -->"


def render(nodes, clusters):
    edge_count = sum(len(n.get("edges") or []) for n in nodes.values())
    ref_count = sum(len(n.get("refs") or []) for n in nodes.values())

    out = [
        BEGIN,
        "<!-- Generated by tools/build.py from nodes/*.yaml. Do not edit by hand. -->",
        "",
        f"**{len(nodes)} nodes, {edge_count} typed edges, {ref_count} references "
        f"across {len(clusters)} clusters.**",
        "",
        "Dashed boxes are nodes belonging to another cluster. Click a node to open "
        "its primary reference.",
        "",
    ]

    for cid, title, blurb in clusters:
        members = members_of(nodes, cid)
        if not members:
            continue
        source = diagram(nodes, members, click=lambda n: primary_url(nodes[n]))
        by_year = sorted(members, key=lambda n: (nodes[n].get("year") or 9999, n))

        out += [f"### {title}", "", blurb, "", "```mermaid", source, "```", "",
                "<details>", f"<summary>{len(members)} nodes</summary>", ""]
        for nid in by_year:
            node = nodes[nid]
            year = f" *({node['year']})*" if node.get("year") else ""
            out.append(
                f"- [`{nid}`](nodes/{nid}.yaml) — "
                f"**{node['title']}**{year}. {clean(node['summary'])}"
            )
        out += ["", "</details>", ""]

    out.append(END)
    return "\n".join(out)


def main():
    check = "--check" in sys.argv

    try:
        nodes, clusters = load_all()
    except Problem as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    text = README.read_text()
    if BEGIN not in text or END not in text:
        print(f"error: README.md is missing {BEGIN} / {END} markers", file=sys.stderr)
        return 1

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + render(nodes, clusters) + tail

    if check:
        if updated != text:
            print("error: README.md is stale; run python3 tools/build.py", file=sys.stderr)
            return 1
        print(f"ok: {len(nodes)} nodes valid, README up to date")
        return 0

    README.write_text(updated)
    edge_count = sum(len(n.get("edges") or []) for n in nodes.values())
    print(f"ok: {len(nodes)} nodes, {edge_count} edges -> README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
