#!/usr/bin/env python3
"""Validate the node graph and regenerate the generated section of the README.

    python3 tools/build.py           # validate, then rewrite README
    python3 tools/build.py --check   # validate only, fail if README is stale
"""

import sys

from graph import (
    ROOT,
    Problem,
    load_all,
    members_of,
    primary_url,
)

README = ROOT / "README.md"
SITE = "https://kvark.github.io/graphics"
BEGIN = "<!-- BEGIN GENERATED -->"
END = "<!-- END GENERATED -->"


def render(nodes, clusters):
    """A compact index only.

    The diagrams live on the site, which can pan, zoom and link. Duplicating
    them here would be a second view of the same thing, drifting apart.
    """
    edge_count = sum(len(n.get("edges") or []) for n in nodes.values())
    linked = sum(1 for n in nodes.values() if primary_url(n))

    out = [
        BEGIN,
        "<!-- Generated by tools/build.py from nodes/*.yaml. Do not edit by hand. -->",
        "",
        f"**{len(nodes)} nodes · {edge_count} typed edges · {linked} anchored to a "
        f"source or article · {len(clusters)} clusters.**",
        "",
        "| Cluster | Nodes | |",
        "| --- | --: | --- |",
    ]

    for cid, title, blurb in clusters:
        members = members_of(nodes, cid)
        if not members:
            continue
        out.append(f"| [{title}]({SITE}/c/{cid}.html) | {len(members)} | {blurb} |")

    out += ["", END]
    return "\n".join(out)


def main():
    check = "--check" in sys.argv

    try:
        nodes, clusters = load_all()
    except Problem as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    text = README.read_text()
    if BEGIN not in text or END not in text:
        print(f"error: README.md is missing {BEGIN} / {END} markers", file=sys.stderr)
        return 1

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + render(nodes, clusters) + tail

    if check:
        if updated != text:
            print("error: README.md is stale; run python3 tools/build.py", file=sys.stderr)
            return 1
        print(f"ok: {len(nodes)} nodes valid, README up to date")
        return 0

    README.write_text(updated)
    edge_count = sum(len(n.get("edges") or []) for n in nodes.values())
    print(f"ok: {len(nodes)} nodes, {edge_count} edges -> README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
